Глава "Формы"
javascriptru/ng-book2-ru pull request #4
Opened 2017-10-28 04:07 UTC by zhuravlyov

Черновой вариант

2017-11-05 18:09 UTC, stevermeister requested changes

2017-11-05 18:09 UTC, stevermeister commented on chapters/forms.md
> +Вероятнее всего, формы являются наиболее важной частью веб-приложения.
> Вероятнее всего

2017-11-05 18:09 UTC, stevermeister commented on chapters/forms.md
> +* Пользовательский интерфейс должен: быть предсказуемым и четко обрабатывать ошибки, в случае их появления
лишнее двоеточие

2017-11-05 18:09 UTC, stevermeister commented on chapters/forms.md
> +`FormControl` представляет собой одно поле ввода - это наименьшая часть формы в Angular.
> наименьшая часть формы

2017-11-05 18:09 UTC, stevermeister commented on chapters/forms.md
> +Две основные функции, которые мы будем использовать в `FormBuilder`:
2 метода

2017-11-05 18:09 UTC, stevermeister commented on chapters/forms.md
> +Теперь заметьте, синтаксис для `ngModel` смешон: мы используем квадратные и круглые скобки вокруг атрибута `ngModel`! Идея состоит в том, что мы используем квадратные скобки для _ввода_, а круглые дл
может перефразировать "смешон"?

2017-11-05 18:09 UTC, stevermeister commented on chapters/forms.md
> +<<[code/forms/src/app/demo-form-with-validations-explicit/demo-form-with-validations-explicit.component.ts](code/forms/src/app/demo-form-with-validations-explicit/demo-form-with-validations-explicit.
тут похоже верстка поломалась

2017-11-06 02:54 UTC, zhuravlyov commented on chapters/forms.md
> +<<[code/forms/src/app/demo-form-with-validations-explicit/demo-form-with-validations-explicit.component.ts](code/forms/src/app/demo-form-with-validations-explicit/demo-form-with-validations-explicit.
fixed

2017-11-06 07:01 UTC, zhuravlyov commented
fixes done!

2017-11-06 07:04 UTC, stevermeister commented on chapters/forms.md
> +`NgModel` это специальная директива: она связывает модель с формой. Особенность `ngModel` в том, что он реализует **двустороннюю связь**. Двусторонняя связь данных почти всегда сложнее и труднее для
вот тут еще верстка ломается

2017-11-06 07:06 UTC, closed without merging